// features/book/components/book-card.tsx
import { BookCover, BookCoverSkeleton } from '@/features/book/components/book-cover';
import { buildHref } from '@/lib/url-state';
import type { BookSummary } from '@/features/book/book-queries';
import type { SearchParams } from '@/lib/url-state';
import Link from 'next/link';
import type { Route } from 'next';

const GRID_SIZES =
  '(min-width: 1280px) 14vw, (min-width: 1024px) 16vw, (min-width: 768px) 20vw, (min-width: 640px) 25vw, 33vw';

type Props = {
  book: BookSummary;
  priority: boolean;
  searchParams: SearchParams;
};

export function BookCard({ book, priority, searchParams }: Props) {
  const back = buildHref(searchParams);
  const href = (back === '/' ? `/${book.id}` : `/${book.id}?${back.slice(2)}`) as Route;

  return (
    <Link
      className="focus-visible:ring-action focus-visible:ring-offset-surface dark:focus-visible:ring-offset-surface-dark group relative block rounded-md transition-transform duration-200 ease-out hover:z-10 hover:scale-[1.04] focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none"
      href={href}
      prefetch={true}
    >
      <BookCover
        className="group-hover:shadow-soft transition-shadow"
        priority={priority}
        sizes={GRID_SIZES}
        src={book.image_url}
        thumbhash={book.thumbhash}
        title={book.title}
      />
      <span className="sr-only">{book.title}</span>
    </Link>
  );
}

export function BookCardSkeleton() {
  return <BookCoverSkeleton />;
}

// app/components/BookCard.vue
<script setup lang="ts">
import { stringifySearchParams } from '#shared/utils/url-state';
import type { BookSummary } from '#shared/types/book';
import type { SearchParams } from '#shared/utils/url-state';

const props = defineProps<{
  book: BookSummary;
  eagerPrefetch: boolean;
  priority: boolean;
  searchParams: SearchParams;
}>();

const href = computed(() => {
  const query = stringifySearchParams(props.searchParams);
  return query ? `/${props.book.id}?${query}` : `/${props.book.id}`;
});
</script>

<template>
  <NuxtLink
    class="focus-visible:ring-action focus-visible:ring-offset-surface dark:focus-visible:ring-offset-surface-dark group relative block rounded-md transition-transform duration-200 ease-out hover:z-10 hover:scale-[1.04] focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none"
    :prefetch-on="eagerPrefetch ? 'visibility' : 'interaction'"
    :to="href"
  >
    <BookCover
      class="group-hover:shadow-soft transition-shadow"
      :priority="priority"
      sizes="sm:25vw md:20vw lg:16vw xl:14vw"
      :src="book.image_url"
      :thumbhash="book.thumbhash"
      :title="book.title"
    />
    <span class="sr-only">{{ book.title }}</span>
  </NuxtLink>
</template>
