// app/components/FastLink.vue
<script setup lang="ts">
import type { RouteLocationRaw } from 'vue-router';

defineOptions({ inheritAttrs: false });

defineProps<{
  prefetchOn?: 'visibility' | 'interaction' | Partial<{ interaction: boolean; visibility: boolean }>;
  to: RouteLocationRaw;
}>();

const emit = defineEmits<{ pressNavigate: [] }>();
let navigatedOnMouseDown = false;
let triggeringClick = false;
let resetTimer: ReturnType<typeof setTimeout> | undefined;

function shouldNavigate(event: MouseEvent) {
  const anchor = event.currentTarget as HTMLAnchorElement;
  const target = event.target instanceof Element ? event.target : undefined;
  const interactiveTarget = target?.closest(
    'button, input, select, textarea, [contenteditable="true"], [role="button"]',
  );

  return (
    !interactiveTarget &&
    (!anchor.target || anchor.target === '_self') &&
    !event.metaKey &&
    !event.ctrlKey &&
    !event.shiftKey &&
    !event.altKey &&
    !anchor.hasAttribute('download') &&
    event.button === 0
  );
}

function handleMouseDown(event: MouseEvent) {
  if (!shouldNavigate(event)) return;

  triggeringClick = true;
  try {
    emit('pressNavigate');
    (event.currentTarget as HTMLAnchorElement).click();
  } finally {
    triggeringClick = false;
  }
  navigatedOnMouseDown = true;
  clearTimeout(resetTimer);
  resetTimer = setTimeout(() => (navigatedOnMouseDown = false), 500);
  event.preventDefault();
}

function handleClick(event: MouseEvent) {
  if (triggeringClick || !navigatedOnMouseDown) return;

  clearTimeout(resetTimer);
  navigatedOnMouseDown = false;
  event.preventDefault();
  event.stopImmediatePropagation();
}

onBeforeUnmount(() => clearTimeout(resetTimer));
</script>

<template>
  <NuxtLink
    v-bind="$attrs"
    :prefetch-on="prefetchOn"
    :to="to"
    @click.capture="handleClick"
    @mousedown="handleMouseDown"
  >
    <slot />
  </NuxtLink>
</template>

// components/ui/fast-link.tsx
'use client';

import Link from 'next/link';
import { useRef } from 'react';

export function FastLink({ onClick, onMouseDown, ...props }: React.ComponentProps<typeof Link>) {
  const navigatedOnMouseDown = useRef(false);
  const resetTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  return (
    <Link
      {...props}
      onMouseDown={event => {
        const target = event.currentTarget.getAttribute('target');
        const interactiveTarget =
          event.target instanceof Element
            ? event.target.closest('button, input, select, textarea, [contenteditable="true"], [role="button"]')
            : null;
        const shouldNavigate =
          !interactiveTarget &&
          (!target || target === '_self') &&
          !event.metaKey &&
          !event.ctrlKey &&
          !event.shiftKey &&
          !event.altKey &&
          !event.currentTarget.hasAttribute('download') &&
          event.button === 0;

        if (!shouldNavigate) {
          onMouseDown?.(event);
          return;
        }

        event.currentTarget.click();
        navigatedOnMouseDown.current = true;
        clearTimeout(resetTimer.current);
        resetTimer.current = setTimeout(() => {
          navigatedOnMouseDown.current = false;
        }, 500);
        event.preventDefault();
        onMouseDown?.(event);
      }}
      onClick={event => {
        if (navigatedOnMouseDown.current) {
          clearTimeout(resetTimer.current);
          navigatedOnMouseDown.current = false;
          event.preventDefault();
          return;
        }

        onClick?.(event);
      }}
    />
  );
}
