// app/components/BookGrid.vue
<script setup lang="ts">
import { getCurrentPage } from '#shared/utils/url-state';
import type { BookSummary } from '#shared/types/book';
import type { SearchParams } from '#shared/utils/url-state';

const props = defineProps<{ books: BookSummary[]; searchParams: SearchParams }>();
const eagerPrefetch = computed(() => getCurrentPage(props.searchParams) === 1);
</script>

<template>
  <EmptyState
    v-if="books.length === 0"
    body="Nothing matched these filters. Try widening the year range or clearing the search."
    title="No books found"
  />
  <div v-else class="grid grid-cols-3 gap-4 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 xl:grid-cols-7">
    <BookCard
      v-for="(book, index) in books"
      :key="book.id"
      :book="book"
      :eager-prefetch="eagerPrefetch"
      :priority="index < 10"
      :search-params="searchParams"
    />
  </div>
</template>

// features/book/components/book-grid.tsx
import { EmptyState } from '@/components/ui/empty-state';
import { ITEMS_PER_PAGE } from '@/features/book/book-constants';
import { BookCard, BookCardSkeleton } from '@/features/book/components/book-card';
import type { BookSummary } from '@/features/book/book-queries';
import { getCurrentPage, type SearchParams } from '@/lib/url-state';

const gridClass = 'grid grid-cols-3 gap-4 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 xl:grid-cols-7';

export function BookGrid({ books, searchParams }: { books: BookSummary[]; searchParams: SearchParams }) {
  if (books.length === 0) {
    return (
      <EmptyState
        body="Nothing matched these filters. Try widening the year range or clearing the search."
        title="No books found"
      />
    );
  }

  const eagerPrefetch = getCurrentPage(searchParams) === 1;

  return (
    <div className={gridClass}>
      {books.map((book, index) => (
        <BookCard
          book={book}
          eagerPrefetch={eagerPrefetch}
          key={book.id}
          priority={index < 10}
          searchParams={searchParams}
        />
      ))}
    </div>
  );
}

export function BookGridSkeleton({ count = ITEMS_PER_PAGE }: { count?: number }) {
  return (
    <div aria-hidden className={gridClass}>
      {Array.from({ length: count }).map((_, index) => (
        <BookCardSkeleton key={index} />
      ))}
    </div>
  );
}
